// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var addOrientationMethod;
    addOrientationMethod = function(name) {
      return chai.Assertion.addMethod(name, function(orientation) {
        var actual, block, expected;
        block = this._obj;
        if (block.cover != null) {
          if (orientation != null) {
            expected = orientation;
            actual = block.cover.orientation;
            return this.assert(expected === actual, "expected block " + block.id + " to have a cover with \#{exp} orientation but got \#{act}", "expected block " + block.id + " to have a cover without \#{exp} orientation but got \#{act}", expected, actual);
          } else {
            return this.assert(block.cover.orientation != null, "expected block " + block.id + " to have a cover with an orientation", "expected block " + block.id + " to have a cover without an orientation");
          }
        }
      });
    };
    addOrientationMethod("orientation");
    return addOrientationMethod("oriented");
  };

}).call(this);
