// Generated by CoffeeScript 1.9.2
(function() {
  var _subtypeOf;

  _subtypeOf = require("../block/_subtypeOf");

  module.exports = function(chai, utils) {
    return chai.Assertion.addProperty("repost", function() {
      var block, content, e, expectedLength, expectedType, item, itemIsValid, lengthIsValid, typeIsValid;
      item = this._obj;
      content = item.content;
      block = this._obj.content[0];
      expectedLength = 1;
      expectedType = "media";
      try {
        _subtypeOf.call(this, block, expectedType);
        typeIsValid = true;
      } catch (_error) {
        e = _error;
        typeIsValid = false;
      }
      lengthIsValid = content.length === expectedLength;
      itemIsValid = lengthIsValid && typeIsValid;
      if (!itemIsValid) {
        if (!lengthIsValid) {
          return this.assert(lengthIsValid, "expected item " + item.id + " content length to be \#{exp} but got \#{act}", "expected item " + item.id + " content length to not be \#{exp} but got \#{act}", expectedLength, content.length);
        } else {
          return _subtypeOf.call(this, block, expectedType);
        }
      }
    });
  };

}).call(this);
