// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var overwrite, overwriteAboveMethod, overwriteBelowMethod, overwriteLeastMethod, overwriteMostMethod;
    overwrite = require("../../assertion/overwrite")(chai, utils);
    overwriteLeastMethod = function(name) {
      return overwrite.method(name, "at least");
    };
    overwriteMostMethod = function(name) {
      return overwrite.method(name, "at most");
    };
    overwriteAboveMethod = function(name) {
      return overwrite.method(name, "above");
    };
    overwriteBelowMethod = function(name) {
      return overwrite.method(name, "below");
    };
    overwriteLeastMethod("least");
    overwriteLeastMethod("gte");
    overwriteMostMethod("most");
    overwriteMostMethod("lte");
    overwriteAboveMethod("above");
    overwriteAboveMethod("gt");
    overwriteAboveMethod("greaterThan");
    overwriteBelowMethod("below");
    overwriteBelowMethod("lt");
    return overwriteBelowMethod("lessThan");
  };

}).call(this);
