// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils, keyName) {
    var _overwriteMethod, overwriteChainableMethod, overwriteContainsMethod, overwriteMethod;
    _overwriteMethod = function(preposition) {
      return function(_super) {
        return function(expected) {
          var actual, block, e, negated, property, propertyName, result;
          block = this._obj;
          propertyName = utils.flag(this, "block.propertyName");
          property = block[propertyName];
          if (property != null) {
            negated = utils.flag(this, "negate");
            actual = property[keyName];
            utils.flag(this, "object", actual);
            try {
              _super.apply(this, arguments);
              result = true;
            } catch (_error) {
              e = _error;
              result = false;
            }
            return this.assert(negated ? !result : result, "expected block " + block.id + " to have a " + propertyName + " " + keyName + " " + preposition + " \#{exp} but got \#{act}", "expected block " + block.id + " to not have a " + propertyName + " " + keyName + " " + preposition + " \#{exp} but got \#{act}", expected, actual);
          } else {
            return _super.apply(this, arguments);
          }
        };
      };
    };
    overwriteMethod = function(name, preposition) {
      var method;
      method = _overwriteMethod(preposition);
      return chai.Assertion.overwriteMethod(name, method);
    };
    overwriteChainableMethod = function(name, preposition) {
      var method, property;
      method = _overwriteMethod(preposition);
      property = function(_super) {
        return _super;
      };
      return chai.Assertion.overwriteChainableMethod(name, method, property);
    };
    overwriteContainsMethod = function(name) {
      return overwriteChainableMethod(name, "that contains");
    };
    overwriteContainsMethod("include");
    overwriteContainsMethod("includes");
    overwriteContainsMethod("contain");
    return overwriteContainsMethod("contains");
  };

}).call(this);
