// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var overwrite, overwriteContainsMethod;
    overwrite = require("../../assertion/overwrite")(chai, utils);
    overwriteContainsMethod = function(name) {
      return overwrite.chainableMethod(name, "that contains");
    };
    overwriteContainsMethod("include");
    overwriteContainsMethod("includes");
    overwriteContainsMethod("contain");
    return overwriteContainsMethod("contains");
  };

}).call(this);
