// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var overwrite, overwriteDeepEqualMethod, overwriteEqualMethod;
    overwrite = require("../../assertion/overwrite")(chai, utils);
    overwriteEqualMethod = function(name) {
      return overwrite.method(name, "equal to");
    };
    overwriteDeepEqualMethod = function(name) {
      return overwrite.method(name, "deeply equal to");
    };
    overwriteEqualMethod("equal");
    overwriteEqualMethod("equals");
    overwriteEqualMethod("eq");
    overwriteDeepEqualMethod("eql");
    return overwriteDeepEqualMethod("eqls");
  };

}).call(this);
