// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var _overwriteMethod, overwriteAnMethod, overwriteChainableMethod;
    _overwriteMethod = function(preposition) {
      return function(_super) {
        return function(path) {
          var block, target;
          block = this._obj;
          target = utils.getPathValue(path, block);
          if (target != null) {
            utils.flag(this, "block.pathValue", path);
            return this.assert(target != null, "expected block " + block.id + " to have " + preposition + " " + path, "expected block " + block.id + " to not have " + preposition + " " + path);
          } else {
            return _super.apply(this, arguments);
          }
        };
      };
    };
    overwriteChainableMethod = function(name, preposition) {
      var method, property;
      method = _overwriteMethod(preposition);
      property = function(_super) {
        return _super;
      };
      return chai.Assertion.overwriteChainableMethod(name, method, property);
    };
    overwriteAnMethod = function(name) {
      return overwriteChainableMethod(name, name);
    };
    overwriteAnMethod("a");
    return overwriteAnMethod("an");
  };

}).call(this);
