// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var _overwriteMethod, overwriteAnMethod, overwriteChainableMethod, overwriteMethod;
    _overwriteMethod = function(preposition, assertion) {
      return function(_super) {
        return function(propertyName) {
          var block, property;
          switch (propertyName) {
            case "cover":
            case "description":
            case "subtitle":
            case "title":
              block = this._obj;
              utils.flag(this, "block.propertyName", {
                block: block,
                propertyName: propertyName
              });
              property = block[propertyName];
              return this.assert(assertion(property), "expected block " + block.id + " to have a " + propertyName, "expected block " + block.id + " to not have a " + propertyName);
            default:
              return _super.apply(this, arguments);
          }
        };
      };
    };
    overwriteMethod = function(name, preposition, assertion) {
      var method;
      method = _overwriteMethod(preposition, assertion);
      return chai.Assertion.overwriteMethod(name, method);
    };
    overwriteChainableMethod = function(name, preposition, assertion) {
      var method, property;
      method = _overwriteMethod(preposition, assertion);
      property = function(_super) {
        return _super;
      };
      return chai.Assertion.overwriteChainableMethod(name, method, property);
    };
    overwriteAnMethod = function(name) {
      return overwriteChainableMethod(name, "a", function(property) {
        return property != null;
      });
    };
    overwriteAnMethod("a");
    return overwriteAnMethod("an");
  };

}).call(this);
