// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var overwrite;
    overwrite = require("../../assertion/overwrite")(chai, utils);
    return overwrite.chainableMethod("length", "with length of", "length");
  };

}).call(this);
