// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    var _overwriteMethod, overwriteAboveMethod, overwriteBelowMethod, overwriteChainableMethod, overwriteLeastMethod, overwriteMethod, overwriteMostMethod;
    _overwriteMethod = function(preposition) {
      return function(_super) {
        return function(expected) {
          var actual, block, e, negated, property, propertyName, result;
          block = this._obj;
          propertyName = utils.flag(this, "block.propertyName");
          property = block[propertyName];
          if ((property != null ? property.length : void 0) != null) {
            negated = utils.flag(this, "negate");
            actual = property;
            utils.flag(this, "object", actual);
            try {
              _super.apply(this, arguments);
              result = true;
            } catch (_error) {
              e = _error;
              result = false;
            }
            return this.assert(negated ? !result : result, "expected block " + block.id + " to have a " + propertyName + " with length " + preposition + " \#{exp} but length was \#{act}", "expected block " + block.id + " to not have a " + propertyName + " with length " + preposition + " \#{exp} but length was \#{act}", expected, actual);
          } else {
            return _super.apply(this, arguments);
          }
        };
      };
    };
    overwriteMethod = function(name, preposition) {
      var method;
      method = _overwriteMethod(preposition);
      return chai.Assertion.overwriteMethod(name, method);
    };
    overwriteChainableMethod = function(name, preposition) {
      var method, property;
      method = _overwriteMethod(preposition);
      property = function(_super) {
        return _super;
      };
      return chai.Assertion.overwriteChainableMethod(name, method, property);
    };
    overwriteLeastMethod = function(name) {
      return overwriteMethod(name, "at least");
    };
    overwriteMostMethod = function(name) {
      return overwriteMethod(name, "at most");
    };
    overwriteAboveMethod = function(name) {
      return overwriteMethod(name, "above");
    };
    overwriteBelowMethod = function(name) {
      return overwriteMethod(name, "below");
    };
    overwriteChainableMethod("length", "of");
    overwriteLeastMethod("least");
    overwriteLeastMethod("gte");
    overwriteMostMethod("most");
    overwriteMostMethod("lte");
    overwriteAboveMethod("above");
    overwriteAboveMethod("gt");
    overwriteAboveMethod("greaterThan");
    overwriteBelowMethod("below");
    overwriteBelowMethod("lt");
    return overwriteBelowMethod("lessThan");
  };

}).call(this);
