// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(block, expectedType) {
    var stringified;
    stringified = JSON.stringify(block);
    return this.assert(require("flowerflip/lib/schema").isSubtypeOf(block != null ? block.type : void 0, expectedType), "expected " + stringified + " to be a subtype of \#{exp} but got \#{act}", "expected " + stringified + " to not be a subtype of \#{exp}", expectedType, block != null ? block.type : void 0);
  };

}).call(this);
