// Generated by CoffeeScript 1.9.2
(function() {
  var cover, description, ofType, repost, subtitle, subtypeOf, title;

  repost = require("./item/repost");

  cover = require("./block/cover");

  description = require("./block/description");

  title = require("./block/title");

  subtitle = require("./block/subtitle");

  ofType = require("./block/ofType");

  subtypeOf = require("./block/subtypeOf");

  module.exports = function(chai, utils) {
    repost(chai, utils);
    cover(chai, utils);
    description(chai, utils);
    title(chai, utils);
    subtitle(chai, utils);
    ofType(chai, utils);
    return subtypeOf(chai, utils);
  };

}).call(this);
