// Generated by CoffeeScript 1.9.2
(function() {
  var comparison, contains, cover, equality, existence, length, ofType, repost, subtypeOf;

  repost = require("./item/repost");

  ofType = require("./block/ofType");

  subtypeOf = require("./block/subtypeOf");

  contains = require("./block/helpers/contains");

  comparison = require("./block/helpers/comparison");

  equality = require("./block/helpers/equality");

  existence = require("./block/helpers/existence");

  length = require("./block/helpers/length");

  cover = require("./block/cover");

  module.exports = function(chai, utils) {
    repost.apply(this, arguments);
    ofType.apply(this, arguments);
    subtypeOf.apply(this, arguments);
    contains.apply(this, arguments);
    comparison.apply(this, arguments);
    equality.apply(this, arguments);
    existence.apply(this, arguments);
    length.apply(this, arguments);
    return cover.apply(this, arguments);
  };

}).call(this);
