// Generated by CoffeeScript 1.9.2
(function() {
  var comparison, contains, equality, existence, length, methods, ofType, properties, repost, subtypeOf;

  methods = require("./assertion/methods");

  properties = require("./assertion/properties");

  repost = require("./item/repost");

  ofType = require("./block/ofType");

  subtypeOf = require("./block/subtypeOf");

  contains = require("./block/helpers/contains");

  comparison = require("./block/helpers/comparison");

  equality = require("./block/helpers/equality");

  existence = require("./block/helpers/existence");

  length = require("./block/helpers/length");

  module.exports = function(chai, utils) {
    methods(chai, utils);
    properties(chai, utils);
    repost(chai, utils);
    ofType(chai, utils);
    subtypeOf(chai, utils);
    contains(chai, utils);
    comparison(chai, utils);
    equality(chai, utils);
    existence(chai, utils);
    return length(chai, utils);
  };

}).call(this);
