// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils, property) {
    return chai.Assertion.addProperty(property, function() {
      var block;
      block = this._obj;
      return this.assert(block[property] != null, "expected block " + block.id + " to have a '" + property + "'", "expected block " + block.id + " to not have a '" + property + "'");
    });
  };

}).call(this);
