// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(block, expected) {
    var actual;
    actual = block != null ? block.type : void 0;
    return this.assert(require("flowerflip/lib/schema").isSubtypeOf(actual, expected), "expected block " + block.id + " to be a subtype of \#{exp} but got \#{act}", "expected block " + block.id + " to not be a subtype of \#{exp}", expected, actual);
  };

}).call(this);
