// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(block, expectedType) {
    var actualType, id;
    actualType = block != null ? block.type : void 0;
    id = block != null ? block.id : void 0;
    return this.assert(require("flowerflip/lib/schema").isSubtypeOf(actualType, expectedType), "expected block " + id + " to be a subtype of \#{exp} but got \#{act}", "expected block " + id + " to not be a subtype of \#{exp}", expectedType, actualType);
  };

}).call(this);
