// Generated by CoffeeScript 1.9.2
(function() {
  var equality, existence;

  equality = require("./helpers/equality");

  existence = require("./helpers/existence");

  module.exports = function(chai, utils) {
    var property;
    property = "cover";
    equality.call(this, chai, utils, property);
    return existence.call(this, chai, utils, property);
  };

}).call(this);
