// Generated by CoffeeScript 1.9.2
(function() {
  var _property;

  _property = require("./_property");

  module.exports = function(chai, utils) {
    return _property.call(this, chai, utils, "description");
  };

}).call(this);
