// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    return chai.Assertion.addProperty("html", function() {
      var block;
      block = this._obj;
      utils.flag(this, "block.pathValue", "html");
      return this.assert(block.html != null, "expected block " + block.id + " to have a html", "expected block " + block.id + " to not have a html");
    });
  };

}).call(this);
