// Generated by CoffeeScript 1.9.2
(function() {
  var _subtypeOf;

  _subtypeOf = require("./_subtypeOf");

  module.exports = function(chai, utils) {
    return chai.Assertion.addMethod("subtypeOf", function(expectedType) {
      var block;
      block = this._obj;
      return _subtypeOf.call(this, block, expectedType);
    });
  };

}).call(this);
