// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(chai, utils) {
    return chai.Assertion.addProperty("title", function() {
      var block;
      block = this._obj;
      utils.flag(this, "block.pathValue", "title");
      return this.assert(block.title != null, "expected block " + block.id + " to have a title", "expected block " + block.id + " to not have a title");
    });
  };

}).call(this);
