// Generated by CoffeeScript 1.9.2
(function() {
  var equality, existence, length;

  equality = require("./helpers/equality");

  existence = require("./helpers/existence");

  length = require("./helpers/length");

  module.exports = function(chai, utils) {
    equality.call(this, chai, utils);
    existence.call(this, chai, utils);
    return length.call(this, chai, utils);
  };

}).call(this);
